version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - examples/test-live
    - vendor

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam
    - gosec

linters-settings:
  revive:
    confidence: 0.8

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - examples/test-live
    - vendor
